version: "3.8"
services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    restart: unless-stopped
  resume_parser:
    build:
      context: resume_parser
      dockerfile: Dockerfile
    restart: unless-stopped
    links:
      - mongodb_container
    volumes:
      - ./:/usr/src/app
    ports:
      - "5001:5000"
volumes:
  mongodb_data_container: